const propertiesData = [
  {
    id: 1,
    title: "Seaside Serenity Villa",
    desc: "A stunning 4-bedroom, 3-bathroom villa in a peaceful suburban neighborhood with panoramic ocean views and a private infinity pool. The open-plan living area features floor-to-ceiling windows that flood the space with natural light, making it the perfect retreat for families who love coastal living.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$550,000",
  },
  {
    id: 2,
    title: "Metropolitan Haven",
    desc: "A chic and fully-furnished 2-bedroom apartment with panoramic city views, located in the heart of the downtown district. Residents enjoy access to a rooftop terrace, state-of-the-art gym, and 24-hour concierge service for a truly luxurious urban lifestyle.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Apartment",
    price: "$385,000",
  },
  {
    id: 3,
    title: "Rustic Retreat Cottage",
    desc: "An elegant 3-bedroom, 2.5-bathroom townhouse in a gated community surrounded by lush greenery and tranquil walking trails. The modern kitchen features quartz countertops and stainless steel appliances, while the backyard boasts a beautifully landscaped garden with a stone patio.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Townhouse",
    price: "$420,000",
  },
  {
    id: 4,
    title: "Skyline Penthouse",
    desc: "A breathtaking 3-bedroom penthouse on the 45th floor with 360-degree views of the city skyline and bay. This corner unit features floor-to-ceiling windows, a private terrace with a hot tub, and custom Italian marble flooring throughout the living spaces.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Penthouse",
    price: "$1,250,000",
  },
  {
    id: 5,
    title: "Garden Oasis",
    desc: "A charming 2-bedroom garden apartment nestled in a quiet tree-lined street with a private courtyard and rose garden. The recently renovated interior boasts hardwood floors, exposed brick walls, and a chef's kitchen with farmhouse sink and butcher block countertops.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Apartment",
    price: "$310,000",
  },
  {
    id: 6,
    title: "Oceanfront Paradise",
    desc: "A magnificent 5-bedroom beachfront estate with direct access to a private white sand beach and breathtaking sunrise views. The property features a saltwater pool, outdoor kitchen, cinema room, and a master suite with a spa-inspired en-suite bathroom.",
    bedroom: "5-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Villa",
    price: "$1,890,000",
  },
  {
    id: 7,
    title: "Urban Edge Condo",
    desc: "A sleek 1-bedroom condo in a newly developed high-rise with smart home technology and energy-efficient design. The open-concept layout maximizes every square foot with custom built-in storage, a Murphy bed, and a balcony overlooking the vibrant city streets below.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Condo",
    price: "$275,000",
  },
  {
    id: 8,
    title: "Heritage Manor",
    desc: "A meticulously restored Victorian home featuring 4 bedrooms, original crown moldings, and a wraparound porch with swing. The property sits on a half-acre lot with mature oak trees, a detached two-car garage, and a finished basement with wine cellar.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$675,000",
  },
  {
    id: 9,
    title: "Lakeside Haven",
    desc: "A peaceful 3-bedroom cottage on the shores of Crystal Lake with a private dock and boathouse. The rustic-modern interior features a stone fireplace, vaulted cedar ceilings, and a sunroom that offers stunning views of the water throughout all four seasons.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Cottage",
    price: "$495,000",
  },
  {
    id: 10,
    title: "Downtown Studio Loft",
    desc: "A stylish studio loft in a converted warehouse with exposed brick walls, polished concrete floors, and 14-foot ceilings. The unit comes fully furnished with mid-century modern pieces and includes access to a shared rooftop garden and coworking space.",
    bedroom: "Studio",
    bathroom: "1-Bathroom",
    vila: "Studio",
    price: "$220,000",
  },
  {
    id: 11,
    title: "Hilltop Estate",
    desc: "An impressive 6-bedroom hilltop estate with panoramic mountain views and over 5 acres of private land. The grand entrance features a sweeping staircase, the gourmet kitchen includes dual islands, and the backyard offers an infinity pool and tennis court.",
    bedroom: "6-Bedroom",
    bathroom: "5-Bathroom",
    vila: "Villa",
    price: "$2,450,000",
  },
  {
    id: 12,
    title: "Suburban Dream Home",
    desc: "A family-friendly 4-bedroom home in a top-rated school district with a large fenced backyard and updated kitchen. The finished basement offers a playroom and home theater, while the front porch is perfect for evening gatherings with neighbors and friends.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$580,000",
  },
  {
    id: 13,
    title: "Riverfront Residence",
    desc: "A contemporary 3-bedroom townhouse along the riverwalk with floor-to-ceiling windows and a private rooftop deck. The open-plan design seamlessly connects the living, dining, and kitchen areas, while the master suite features a luxurious soaking tub with river views.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Townhouse",
    price: "$625,000",
  },
  {
    id: 14,
    title: "The Collector's Loft",
    desc: "A spacious 2-bedroom corner loft with oversized windows and an additional flex room perfect for an art studio or home gallery. The chef's kitchen boasts professional-grade appliances, and the building offers a private wine storage facility for residents.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Loft",
    price: "$440,000",
  },
  {
    id: 15,
    title: "Forest Haven Cabin",
    desc: "A cozy 3-bedroom log cabin nestled deep in the pine forest with a stone fireplace, hot tub, and wraparound deck. The property includes a guest house and access to miles of hiking trails, making it the perfect weekend getaway or vacation rental investment.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Cabin",
    price: "$365,000",
  },
  {
    id: 16,
    title: "Palm Court Villa",
    desc: "A luxurious 4-bedroom villa in an exclusive gated resort community with golf course views and club membership included. The Mediterranean-style home features a courtyard with fountain, outdoor fireplace, and a saltwater pool surrounded by palm trees.",
    bedroom: "4-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Villa",
    price: "$895,000",
  },
  {
    id: 17,
    title: "The Minimalist Flat",
    desc: "A bright and airy 1-bedroom flat with minimalist Scandinavian design, smart storage solutions, and floor-to-ceiling windows. The building offers a fitness center, co-working lounge, and a rooftop pool with panoramic views of the surrounding neighborhood.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Apartment",
    price: "$298,000",
  },
  {
    id: 18,
    title: "Bayside Bungalow",
    desc: "A charming 2-bedroom bungalow just steps from the bay with a screened porch, outdoor shower, and mature tropical landscaping. The recently updated interior features shiplap walls, bamboo flooring, and a custom kitchen with marble countertops and brass fixtures.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Bungalow",
    price: "$340,000",
  },
  {
    id: 19,
    title: "The Governor's Suite",
    desc: "A stately 5-bedroom colonial revival mansion on a tree-lined historic boulevard with a carriage house and English garden. Original details include stained glass windows, mahogany paneling, and a grand foyer with a sweeping staircase and crystal chandelier.",
    bedroom: "5-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Villa",
    price: "$1,450,000",
  },
  {
    id: 20,
    title: "Tech Park Condo",
    desc: "A modern 2-bedroom condo in the vibrant tech district with an open floor plan, smart home automation, and electric vehicle charging in the garage. The building features a rooftop terrace with BBQ stations, a pet spa, and a virtual reality gaming room.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Condo",
    price: "$475,000",
  },
  {
    id: 21,
    title: "Sunset Terrace",
    desc: "A stunning 3-bedroom duplex with a wrap-around terrace offering unobstructed sunset views over the city skyline and hills beyond. The upper level features a private roof garden with built-in seating and an outdoor kitchen for al fresco dining and entertaining guests.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Duplex",
    price: "$720,000",
  },
  {
    id: 22,
    title: "Willow Creek Estate",
    desc: "A sprawling 5-bedroom ranch estate on 10 acres with a stocked pond, stables, and riding trails through picturesque meadows and wooded areas. The main house features a chef's kitchen, great room with two-story stone fireplace, and a screened-in pool and spa area.",
    bedroom: "5-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Villa",
    price: "$1,675,000",
  },
  {
    id: 23,
    title: "The Artistic Flat",
    desc: "A vibrant 1-bedroom flat in the arts district with original hardwood floors, exposed brick, and large windows that flood the space with natural light throughout the day. The rental includes one dedicated parking space and access to a communal courtyard garden with seating areas.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Apartment",
    price: "$255,000",
  },
  {
    id: 24,
    title: "Creekside Cottage",
    desc: "A delightful 2-bedroom cottage beside a babbling creek with a footbridge, wildflower garden, and fire pit area for cozy evenings under the stars. The interior is warm and inviting with a wood-burning stove, built-in bookshelves, and a sun-drenched breakfast nook.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Cottage",
    price: "$315,000",
  },
  {
    id: 25,
    title: "The Penthouse Collection",
    desc: "An exquisite 4-bedroom penthouse occupying the entire top floor with a private elevator, 360-degree terrace, and a dedicated wine room with climate control. The master suite features dual walk-in closets, a steam shower, and a private balcony with outdoor fireplace.",
    bedroom: "4-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Penthouse",
    price: "$2,100,000",
  },
  {
    id: 26,
    title: "Harbor View Townhouse",
    desc: "A sophisticated 3-bedroom townhouse overlooking the marina with a rooftop terrace, private garage, and direct waterfront access for your boat. The gourmet kitchen features waterfall marble islands, and the living room opens to a terrace with built-in gas fireplace.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Townhouse",
    price: "$780,000",
  },
  {
    id: 27,
    title: "Mountain Peaks Lodge",
    desc: "A grand 6-bedroom ski lodge with a private chairlift, hot springs pool, and panoramic views of the surrounding peaks and alpine forests. The great room features a three-story stone fireplace, and the game room includes a bowling alley and home theater with stadium seating.",
    bedroom: "6-Bedroom",
    bathroom: "5-Bathroom",
    vila: "Villa",
    price: "$2,850,000",
  },
  {
    id: 28,
    title: "Mid-Century Modern Gem",
    desc: "A lovingly preserved 3-bedroom mid-century modern home with original butterfly roof, floor-to-ceiling windows, and a kidney-shaped pool in the backyard. The property has been updated with energy-efficient systems while maintaining its authentic retro charm and character.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$525,000",
  },
  {
    id: 29,
    title: "City Lights Condo",
    desc: "A sleek 2-bedroom high-rise condo with floor-to-ceiling windows showcasing dazzling city lights and mountain views on clear days. Residents enjoy concierge service, a infinity-edge lap pool, yoga studio, and a private cinema room available for booking gatherings.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Condo",
    price: "$510,000",
  },
  {
    id: 30,
    title: "The Vineyard House",
    desc: "A romantic 3-bedroom farmhouse nestled among rolling vineyards with a private wine cellar, tasting room, and outdoor kitchen overlooking the vines. The property produces up to 500 cases of wine annually and includes a caretaker's cottage and equipment barn.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$925,000",
  },
  {
    id: 31,
    title: "Zen Garden Retreat",
    desc: "A serene 2-bedroom Japanese-inspired home with a koi pond, meditation garden, bamboo grove, and a traditional tea house for quiet reflection and relaxation. The open-concept interior uses natural materials like cedar, stone, and rice paper screens throughout the living spaces.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$620,000",
  },
  {
    id: 32,
    title: "The Clocktower Loft",
    desc: "A unique 1-bedroom loft inside a converted historic clocktower with original timepiece mechanisms, circular walls, and views across the entire city. The spiral staircase leads to a sleeping loft, and the kitchen features custom cabinetry that follows the curved walls.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Loft",
    price: "$390,000",
  },
  {
    id: 33,
    title: "Tropical Paradise Villa",
    desc: "A breathtaking 5-bedroom beachfront villa with an infinity pool, tiki bar, and lush tropical landscaping with mango and coconut trees scattered throughout the grounds. Outdoor spaces include a lanai with dining for twelve, fire pit, and hammock garden for relaxation.",
    bedroom: "5-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Villa",
    price: "$1,550,000",
  },
  {
    id: 34,
    title: "The Commuter's Condo",
    desc: "A practical and stylish 2-bedroom condo located directly above the metro station with soundproof windows and a balcony overlooking the bustling plaza below. The unit features a home office nook, in-unit laundry, and a storage locker in the secure underground parking garage.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Condo",
    price: "$345,000",
  },
  {
    id: 35,
    title: "Eagle Ridge Estate",
    desc: "A magnificent 4-bedroom contemporary home perched on a ridge with floor-to-ceiling windows framing endless mountain vistas and golden sunsets. The open-concept design features a double-sided fireplace, a wine wall, and a covered terrace with an outdoor kitchen and fireplace.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$890,000",
  },
  {
    id: 36,
    title: "The Carriage House",
    desc: "A charming 1-bedroom converted carriage house behind a historic mansion with original brickwork, exposed beams, and a private courtyard garden with a trickling fountain. The studio-style layout maximizes space with a lofted sleeping area and custom built-in storage solutions.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Studio",
    price: "$280,000",
  },
  {
    id: 37,
    title: "Marina Bay Condo",
    desc: "A luxurious 3-bedroom condo on the marina with a private boat slip, waterfront balcony, and access to the yacht club's dining and fitness facilities. The interior features wide plank white oak floors, a chef's kitchen with marble backsplash, and custom millwork throughout.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Condo",
    price: "$795,000",
  },
  {
    id: 38,
    title: "The Farmhouse",
    desc: "A restored 4-bedroom farmhouse on 20 acres of pasture and woodland with a barn, chicken coop, and organic vegetable garden ready for planting. The country kitchen features a farmhouse sink, wood-burning oven, and a walk-in pantry with butcher block shelving and storage.",
    bedroom: "4-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$620,000",
  },
  {
    id: 39,
    title: "Sky Garden Penthouse",
    desc: "A spectacular 3-bedroom penthouse with a wraparound terrace garden featuring mature olive trees, a reflecting pool, and outdoor shower with city views in every direction. The interior boasts 12-foot ceilings, a customized walk-in closet, and a spa bathroom with steam room.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Penthouse",
    price: "$1,680,000",
  },
  {
    id: 40,
    title: "Beachcomber's Bungalow",
    desc: "A casual 2-bedroom beach bungalow with an outdoor shower, hammock porch, and a sandy path leading directly to the beach for morning walks and evening strolls. The coastal-inspired interior features beadboard walls, driftwood accents, and a surfboard rack in the garage.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Bungalow",
    price: "$425,000",
  },
  {
    id: 41,
    title: "The Atrium House",
    desc: "An innovative 4-bedroom home built around a central atrium with a glass roof, indoor garden, and a koi stream that flows through the main living areas. Each bedroom opens onto the atrium through sliding glass doors, blurring the line between indoors and outdoors.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$1,120,000",
  },
  {
    id: 42,
    title: "Parkview Studio",
    desc: "A bright studio apartment overlooking Central Park with a Juliet balcony, custom Murphy bed, and a kitchenette with Belgian marble countertops and brass fixtures. The building offers a doorman, rooftop sundeck, and a fitness center with virtual training classes.",
    bedroom: "Studio",
    bathroom: "1-Bathroom",
    vila: "Studio",
    price: "$265,000",
  },
  {
    id: 43,
    title: "Canyon View Retreat",
    desc: "A striking 3-bedroom desert modern home with walls of glass framing dramatic canyon views and stunning sunset colors that change throughout the evening. The property features an infinity-edge pool, outdoor shower, and a rooftop observatory with a telescope for stargazing nights.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$740,000",
  },
  {
    id: 44,
    title: "The Brownstone",
    desc: "A classic 4-bedroom brownstone with a stoop, garden level, and original restored details including tin ceilings, claw-foot tubs, and a decorative cast-iron fireplace in the parlor. The top floor features a skylit studio with wet bar and private roof terrace access.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$1,380,000",
  },
  {
    id: 45,
    title: "Lighthouse Keepers Cottage",
    desc: "A picturesque 2-bedroom cottage adjacent to an operating lighthouse with panoramic ocean views, a widow's walk, and the sound of waves crashing against the rocky shore below. The cozy interior features a potbelly stove, ship-lapped walls, and a reading nook in the bay window.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Cottage",
    price: "$450,000",
  },
  {
    id: 46,
    title: "The Greenhouse Residence",
    desc: "An eco-friendly 3-bedroom home with a attached greenhouse, solar panels, rainwater collection system, and sustainable bamboo flooring throughout the open-concept layout. The living wall in the great room purifies the air while providing a stunning backdrop of lush greenery.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$585,000",
  },
  {
    id: 47,
    title: "Harborside Duplex",
    desc: "A dramatic 3-bedroom duplex with a private rooftop terrace, harbor views, and a spiral staircase connecting the two levels of sophisticated urban living space. The lower level features a guest suite with separate entrance, ideal for visitors or rental income potential.",
    bedroom: "3-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Duplex",
    price: "$830,000",
  },
  {
    id: 48,
    title: "The Treehouse Villa",
    desc: "A whimsical 2-bedroom home built among ancient oak trees with rope bridges connecting the main house to a separate studio and lookout tower with panoramic forest views. The interior features reclaimed wood, circular windows, and a living room with a two-story stone fireplace.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$510,000",
  },
  {
    id: 49,
    title: "Corporate Luxury Suite",
    desc: "A refined 2-bedroom executive apartment in the financial district with a boardroom, private study, and butler service available around the clock for busy professionals. The building features a cigar lounge, business center, and a temperature-controlled wine locker for residents.",
    bedroom: "2-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Apartment",
    price: "$650,000",
  },
  {
    id: 50,
    title: "Alpine Chalet",
    desc: "A luxurious 5-bedroom ski chalet with a heated outdoor pool, sauna, and direct slope access for the ultimate winter sports enthusiast and their guests. The great room features a massive stone hearth, while the game room offers a pool table, bar, and cozy fireplace.",
    bedroom: "5-Bedroom",
    bathroom: "4-Bathroom",
    vila: "Chalet",
    price: "$1,920,000",
  },
  {
    id: 51,
    title: "The Sanctuary",
    desc: "A private 4-bedroom gated estate with a meditation pavilion, labyrinth garden, and a natural spring-fed pond stocked with koi and surrounded by weeping willows. The main house uses feng shui principles throughout with a dedicated yoga studio and steam room for wellness.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$1,350,000",
  },
  {
    id: 52,
    title: "Brick & Beam Loft",
    desc: "An authentic 1-bedroom industrial loft in a converted textile factory with original brick walls, wooden ceiling beams, and massive steel-framed windows facing a quiet courtyard. The polished concrete floors have radiant heating, and the bathroom features a soaking tub on a raised platform.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Loft",
    price: "$370,000",
  },
  {
    id: 53,
    title: "Duneside Retreat",
    desc: "A tranquil 3-bedroom coastal home nestled among sand dunes with a boardwalk to the beach, outdoor fireplace, and an observation deck for whale watching and stunning sunsets over the Pacific Ocean horizon in the distance.",
    bedroom: "3-Bedroom",
    bathroom: "2-Bathroom",
    vila: "Villa",
    price: "$680,000",
  },
  {
    id: 54,
    title: "The Penthouse at Park Tower",
    desc: "The crown jewel of Park Tower, this 5-bedroom penthouse spans the entire 60th floor with a private pool, library, and a grand salon with 20-foot ceilings and crystal chandeliers throughout the expansive living and entertaining spaces.",
    bedroom: "5-Bedroom",
    bathroom: "5-Bathroom",
    vila: "Penthouse",
    price: "$3,200,000",
  },
  {
    id: 55,
    title: "Cobblestone Corner",
    desc: "A storybook 2-bedroom cottage on a historic cobblestone street with window boxes, a picket fence, and a secret garden hidden behind a vine-covered trellis gate that opens to a patio with outdoor dining and string lights overhead.",
    bedroom: "2-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Cottage",
    price: "$375,000",
  },
  {
    id: 56,
    title: "Tech Tower Condo",
    desc: "A smart 1-bedroom condo with voice-controlled everything, motorized shades, integrated sound system, and a charging station for all your devices and electric vehicles in the garage below. The building has a drone delivery hub and a robotics workshop for residents to use.",
    bedroom: "1-Bedroom",
    bathroom: "1-Bathroom",
    vila: "Condo",
    price: "$410,000",
  },
  {
    id: 57,
    title: "The Wisteria Villa",
    desc: "A romantic 4-bedroom Mediterranean villa draped in wisteria with a courtyard fountain, terra-cotta roof, and an outdoor pizza oven surrounded by lavender and rosemary bushes filling the air with their enchanting fragrance year after year.",
    bedroom: "4-Bedroom",
    bathroom: "3-Bathroom",
    vila: "Villa",
    price: "$960,000",
  },
  {
    id: 58,
    title: "Riverside Studio",
    desc: "A compact but cleverly designed studio along the river with a transformable furniture system that turns the space from living room to bedroom to home office in seconds. The building offers kayak storage, a bike repair station, and a community garden for green-thumbed residents.",
    bedroom: "Studio",
    bathroom: "1-Bathroom",
    vila: "Studio",
    price: "$195,000",
  },
  {
    id: 59,
    title: "The Ambassador Suite",
    desc: "A palatial 6-bedroom diplomatic residence previously home to foreign ambassadors, featuring a ballroom, formal dining for 24, and a private garden with a reflecting pool and statues that line the manicured pathways and hedge-lined garden rooms.",
    bedroom: "6-Bedroom",
    bathroom: "5-Bathroom",
    vila: "Villa",
    price: "$2,750,000",
  },
  {
    id: 60,
    title: "Sunrise Studio",
    desc: "A cheerful studio apartment on the top floor with eastern exposure, a breakfast bar, and built-in window seat perfect for morning coffee while watching the sunrise paint the sky in brilliant shades of orange, pink, and gold over the city skyline.",
    bedroom: "Studio",
    bathroom: "1-Bathroom",
    vila: "Studio",
    price: "$185,000",
  },
];

export default propertiesData;
